name: Tag

on:
  push:
    branches: [main]

permissions: {}

jobs:
  tag:
    name: Tag
    uses: praxi-labs/ci/.github/workflows/auto-tag.yml@v1
    with:
      version-path: phylax/version.py
    permissions:
      contents: write
